# Generated by Django 4.2.2 on 2023-06-24 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('ligasGanadas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppFutbolArg.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField()),
                ('fecha_hora', models.CharField(max_length=5)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_local', to='AppFutbolArg.equipos')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_visitante', to='AppFutbolArg.equipos')),
            ],
        ),
    ]
