# Generated by Django 4.2.2 on 2023-06-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0002_alter_equipos_options_alter_fixture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'verbose_name_plural': 'Fixture'},
        ),
    ]
