# Generated by Django 4.2.2 on 2023-06-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFutbolArg', '0003_alter_fixture_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixture',
            old_name='fecha_dia',
            new_name='dia',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='fecha_hora',
            new_name='hora',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='equipo_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='equipo_visitante',
            new_name='visitante',
        ),
        migrations.RenameField(
            model_name='posiciones',
            old_name='partidos_jugados',
            new_name='PartidosJugados',
        ),
    ]
